events {}

http {
  server {
    listen 80;

    location /app {
      proxy_pass http://platform:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /landing {
      proxy_pass http://landing-svc:80;
      proxy_set_header Host $host;
    }

    location / {
      return 301 /landing;
    }
  }
}
